site_name: Data Derby

theme:
  name: material
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
      primary: black
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: black

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html

nav:
  - Home: index.md
  # - Question: question/one.md